Document: amxa-millefeuilles
Title: Debian amxa-millefeuilles Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-millefeuilles is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-millefeuilles/amxa-millefeuilles.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-millefeuilles/amxa-millefeuilles.ps.gz

Format: text
Files: /usr/share/doc/amxa-millefeuilles/amxa-millefeuilles.text.gz

Format: HTML
Index: /usr/share/doc/amxa-millefeuilles/html/index.html
Files: /usr/share/doc/amxa-millefeuilles/html/*.html
